apiVersion: v1
kind: Service
metadata:
  labels:
    fwk-ui-svc: fwk-ui
  name: fwk-ui
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ui
    nodePort: 80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: fwk-service-archives
    nodePort: 5762
    port: 5762
    protocol: TCP
    targetPort: 5762
  - name: fwk-service-farm
    nodePort: 5763
    port: 5763
    protocol: TCP
    targetPort: 5763
  - name: fwk-service-parcel
    nodePort: 5764
    port: 5764
    protocol: TCP
    targetPort: 5764
  - name: fwk-service-system
    nodePort: 5765
    port: 5765
    protocol: TCP
    targetPort: 5765
  - name: fwk-service-user
    nodePort: 5766
    port: 5766
    protocol: TCP
    targetPort: 5766
  - name: iss-proxy
    nodePort: 9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: oauth2-proxy
    nodePort: 9300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    fwk-ui-po: fwk-ui
  sessionAffinity: None
  type: NodePort