apiVersion: v1
kind: Service
metadata:
  labels:
    fwk-service-svc: fwk-service-user
  name: fwk-service-user
  namespace: default
spec:
  ports:
  - name: service
    port: 5766
    protocol: TCP
    targetPort: 5766
  selector:
    fwk-service-po: fwk-service-user
  sessionAffinity: None
  type: ClusterIP