apiVersion: v1
kind: Service
metadata:
  labels:
    fwk-service-svc: fwk-service-archives
  name: fwk-service-archives
  namespace: default
spec:
  ports:
  - name: service
    port: 5762
    protocol: TCP
    targetPort: 5762
  selector:
    fwk-service-po: fwk-service-archives
  sessionAffinity: None
  type: ClusterIP