FROM node:8-alpine
WORKDIR /app
COPY . /app
RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
RUN npm install @agrithings/cmap @agrithings/common @vehiclecloud/commons @vehiclecloud/grpc-websocket-client @vehiclecloud/json-schema @vehiclecloud/json-schema-vuetify @vehiclecloud/mongo-rest-client @vehiclecloud/redis-rest-client @vehiclecloud/oauth2-client --registry=http://nexus.agthings.cn:8081/repository/npm-all/
RUN npm install --registry=https://registry.npm.taobao.org
#CMD ["npm", "run", "dev"]
