FROM node:8-alpine AS builder
WORKDIR /app
ADD . /app
RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
RUN npm install @agrithings/cmap @agrithings/common @vehiclecloud/commons @vehiclecloud/grpc-websocket-client @vehiclecloud/json-schema @vehiclecloud/json-schema-vuetify @vehiclecloud/mongo-rest-client @vehiclecloud/redis-rest-client @vehiclecloud/oauth2-client --registry=http://nexus.agthings.cn:8081/repository/npm-all/
RUN npm install --registry=https://registry.npm.taobao.org
RUN ["npm", "run", "build"]

FROM nginx:alpine

ENV AG_MONGO_ISS_DATABASE="iov"
ENV AG_MONGO_ISS_BASE="http://localhost:9000"
ENV AG_MONGO_APP_DATABASE="fob"
ENV AG_MONGO_APP_BASE="http://localhost:9000"
ENV AG_REDIS_BASE="http://localhost:9100"
ENV AG_OAUTH2_CLIENT_ID="10"
ENV AG_OAUTH2_COOKIE_NAME="fob-token"
ENV AG_OAUTH2_SERVER="http://localhost:9300"
ENV AG_FILE_SERVER="http://localhost:9400"
ENV AG_ISS_SERVER="http://localhost:8100"
ENV AG_YZ_SERVER="http://localhost:8101"

RUN sed -i '/index\.htm;/a\        try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY --from=builder /app/dist/js/conf.*.js /usr/share/nginx/html/js/conf.template
CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/js/conf.template > `find /usr/share/nginx/html/js/conf.*.js` && nginx -g 'daemon off;'"]
